### ISSUE TITLE
Whitelist players per command

### ISSUE THREAD

**Issue by ItsKev** [kryonitelabs/kryo-discord-whitelist#7]
**Is your feature request related to a problem? Please describe.**
Currently, only players who are verifying themselves via Discord are able to join the server. We should be able to whitelist players without Discord.

**Describe the solution you'd like**
Implement a command to add and remove players from the whitelist.
`/whitelist add xxx`
`/whitelist remove xxx`

**Comment by lusu007** [comment]
I think `/whitelist remove xxx` should kick the player xxx if he is online.
